apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: "da21ab6d-461f-40a8-ac0e-894f551bf6f1"
      vaultUrl: "https://kv-proj-cluster-vault.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets
